#!/usr/bin/python3

# Global imports
import os
import sys
import argparse

# Resolve custom imports
sys.path.append(".")
os.system("pip3 install rich --user")
from src.Remote.snarl_server import SnarlServer

# Get console arguments
parser = argparse.ArgumentParser()
parser.add_argument('--levels', default='snarl.levels')
parser.add_argument('--clients', type=int, default=4)
parser.add_argument('--wait', type=int, default=60)
parser.add_argument('--observe', action='store_true')
parser.add_argument('--address', default='127.0.0.1')
parser.add_argument('--port', type=int, default=45678)
args = parser.parse_args()

# Launch Server
server = SnarlServer(args.levels, args.clients, args.wait, args.observe, args.address, args.port)
server.launch()
